### ISSUE TITLE
Doesn't compile with TeX Live 2015 (rev 5238)

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-user-guide#1]
```
This is LuaTeX, Version beta-0.80.0 (TeX Live 2015/Arch Linux) (rev 5238) 
 restricted \write18 enabled.
(./manjaro-user-guide.tex
LaTeX2e <2015/01/01>
Babel <3.9l> and hyphenation patterns for 79 languages loaded.

Systemcall.cpp (292): Systemcall: 'lualatex "manjaro-user-guide.tex"' finished with exit code 1
```

Latest working version was:
```
This is LuaTeX, Version beta-0.79.1 (TeX Live 2014/Arch Linux) (rev 4971) 
 restricted \write18 enabled.
(./manjaro-user-guide.tex
LaTeX2e <2014/05/01>
Babel <3.9l> and hyphenation patterns for 79 languages loaded.
```

**Comment by philmmanjaro** [comment]
Same goes for any newer version:
```
This is LuaTeX, Version beta-0.80.0 (TeX Live 2016/dev/Arch Linux) (rev 5238) 
 restricted \write18 enabled.
(./manjaro-user-guide.tex
LaTeX2e <2015/01/01>
Babel <3.9l> and hyphenation patterns for 79 languages loaded.

Systemcall.cpp (292): Systemcall: 'lualatex "manjaro-user-guide.tex"' finished with exit code 1
```

**Comment by jonathonf** [comment]
pdflatex works fine... what changed in lualatex? Hmm.

**Comment by philmmanjaro** [comment]
Can you update the [PKGBUILD](https://github.com/manjaro/packages-extra/blob/master/manjaro-documentation/PKGBUILD) then?

**Comment by jonathonf** [comment]
It looks similar to this: http://tex.stackexchange.com/questions/202142/problems-compiling-tufte-title-page-in-xelatex . I've played with getting the workaround on those answers working in LyX but it doesn't want to play... it worked before without any faffing so I wonder if tufte-book is broken for TeX Live 2015...

Using pdflatex on the command line results in a PDF without correct section bookmarks. Exporting using pdflatex within LyX gives the correct sectioning. Hm.

**Comment by jonathonf** [comment]
Ah, got it:

```bash
lyx --export pdflatex manjaro-user-guide.lyx
pdflatex manjaro-user-guide
pdflatex manjaro-user-guide
```

See [pull request](https://github.com/manjaro/packages-extra/pull/25).
