### ISSUE TITLE
pdf-download

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-user-guide#2]
Do we provide a pdf-download for people who are not yet on a manjaro or arch box?

**Comment by philmmanjaro** [comment]
Yes, as usual on our [sf.net project page](http://sourceforge.net/projects/manjarolinux/files/release/15.09/manjaro-15.09-readme.pdf/download) ...

**Comment by oberon2007** [comment]
ah, ok, thanks! ;)

**Comment by serge-stroobandt** [comment]
You should urgently mention that download link in the README.md of this github repository!
I almost opened a new issue for this.

**Comment by jonathonf** [comment]
I added a link to the download pages in c7008b0.
